config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'accueil', to: 'pages#accueil', as: :accueil
  get 'animation', to: 'pages#animation', as: :animation
  get 'cards', to: 'pages#cards', as: :cards
  get 'carousel', to: 'pages#carousel', as: :carousel
  get 'contact', to: 'pages#contact', as: :contact
  get 'pieddepage', to: 'pages#pieddepage', as: :pieddepage
  get 'icones', to: 'pages#icones', as: :icones
  get 'images', to: 'pages#images', as: :images
  get 'matrix', to: 'pages#matrix', as: :matrix
  get 'nav', to: 'pages#nav', as: :nav
  get 'projects', to: 'pages#projects', as: :projects
  get 'p404', to: 'pages#p404', as: :p404
  get 'ressource', to: 'pages#ressource', as: :ressource
  get 'starwars', to: 'pages#starwars', as: :starwars

  resources :reservations, only: [ :new, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :name, presence: true
  validates :pax, inclusion: { in: 0..9 }
  validates :date, presence: true
  validate :check_date_valid?, on: :create
  validate :check_time_valid?, on: :create

  private

  def check_date_valid?
    if date == Date.today
      errors.add(:date, 'incorrecte pour réserver en ligne. Veuillez téléphoner')
    elsif date < Date.today
      errors.add(:date, 'ne peut être dans le passé !')
    end
  end

  def check_time_valid?
    start_lunch = '12:00'
    end_lunch = '14:00'
    start_diner = '19:00'
    end_diner = '22:00'

    if time < start_lunch
      errors.add(:time, 'Lunch: 12:00-14:00, Diner: 19:00-22:00')
    elsif time > end_lunch && time < start_diner
      errors.add(:time, 'Lunch: 12:00-14:00, Diner: 19:00-22:00')
    elsif time > end_diner
      errors.add(:time, 'Lunch: 12:00-14:00, Diner: 19:00-22:00')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def matrix
  end

  def starwars
  end

  def about
  end

  def carousel
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      mail = ReservationMailer.with(reservation: @reservation).welcome
      mail.delivery_now
    else
      flash.now[:alert] = 'Can\'t send your reservation'
      render :new
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:name, :date, :time, :pax)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name].join(", ")
      end
    end
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-compatible" content="IE=edge,chrome=1">
    <title>Source</title>

    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script>
      var swiper = new Swiper('.myswiper', {
        effect: "coverflow",
        grabCursor: true,
        centeredSlides: true,
        slidesPerView: "auto",
        coverflowEffect: {
          rotate: 20,
          stretch: 0,
          depth: 200,
          modifier: 1,
          slideShadows: true,
        },
        loop: true,
        autoplay: {
          delay: 2500,
          disableOnInteraction: false,
        },
      });
    </script>
  </body>
</html>

app/views/pages/404.html.erb
<div class="container-404">
  <div class="wrapper-404">
    <div class="error-title">
      404
    </div>
    <div class="error-text">
      PAGE NOT FOUND
    </div>
    <div class="error-link">
      <%= link_to 'PAGE D\'ACCUEIL', root_path, class:"btn-error" %>
    </div>
  </div>
</div>

app/views/pages/_dev.html.erb
<div class="developper">
  <svg id="developper" width="366" height="130" viewBox="0 0 366 130" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M60.992 3.39201L48.064 48H41.536L31.168 12.096L20.416 48L13.952 48.064L1.47198 3.39201H7.67999L17.408 41.216L28.16 3.39201H34.688L44.928 41.088L54.72 3.39201H60.992Z" stroke="white"/>
  <path d="M99.3655 29.12C99.3655 30.2293 99.3015 31.4027 99.1735 32.64H71.1415C71.3548 36.096 72.5281 38.8053 74.6615 40.768C76.8375 42.688 79.4615 43.648 82.5335 43.648C85.0508 43.648 87.1415 43.072 88.8055 41.92C90.5122 40.7253 91.7068 39.1467 92.3895 37.184H98.6615C97.7228 40.5547 95.8455 43.3067 93.0295 45.44C90.2135 47.5307 86.7148 48.576 82.5335 48.576C79.2055 48.576 76.2188 47.8293 73.5735 46.336C70.9708 44.8427 68.9228 42.7307 67.4295 40C65.9361 37.2267 65.1895 34.0267 65.1895 30.4C65.1895 26.7733 65.9148 23.5947 67.3655 20.864C68.8162 18.1333 70.8428 16.0427 73.4455 14.592C76.0908 13.0987 79.1202 12.352 82.5335 12.352C85.8615 12.352 88.8055 13.0773 91.3655 14.528C93.9255 15.9787 95.8882 17.984 97.2535 20.544C98.6615 23.0613 99.3655 25.92 99.3655 29.12ZM93.3495 27.904C93.3495 25.6853 92.8588 23.7867 91.8775 22.208C90.8962 20.5867 89.5522 19.3707 87.8455 18.56C86.1815 17.7067 84.3255 17.28 82.2775 17.28C79.3335 17.28 76.8162 18.2187 74.7255 20.096C72.6775 21.9733 71.5041 24.576 71.2055 27.904H93.3495Z" stroke="white"/>
  <path d="M112.877 19.456C114.072 17.3653 115.821 15.6587 118.125 14.336C120.429 13.0133 123.053 12.352 125.997 12.352C129.154 12.352 131.992 13.0987 134.509 14.592C137.026 16.0853 139.01 18.1973 140.461 20.928C141.912 23.616 142.637 26.752 142.637 30.336C142.637 33.8773 141.912 37.0347 140.461 39.808C139.01 42.5813 137.005 44.736 134.445 46.272C131.928 47.808 129.112 48.576 125.997 48.576C122.968 48.576 120.301 47.9147 117.997 46.592C115.736 45.2693 114.029 43.584 112.877 41.536V48H107.053V0.640015H112.877V19.456ZM136.685 30.336C136.685 27.6907 136.152 25.3867 135.085 23.424C134.018 21.4613 132.568 19.968 130.733 18.944C128.941 17.92 126.957 17.408 124.781 17.408C122.648 17.408 120.664 17.9413 118.829 19.008C117.037 20.032 115.586 21.5467 114.477 23.552C113.41 25.5147 112.877 27.7973 112.877 30.4C112.877 33.0453 113.41 35.3707 114.477 37.376C115.586 39.3387 117.037 40.8533 118.829 41.92C120.664 42.944 122.648 43.456 124.781 43.456C126.957 43.456 128.941 42.944 130.733 41.92C132.568 40.8533 134.018 39.3387 135.085 37.376C136.152 35.3707 136.685 33.024 136.685 30.336Z" stroke="white"/>
  <path d="M18.816 67.392C23.68 67.392 27.8827 68.3093 31.424 70.144C35.008 71.936 37.7387 74.5173 39.616 77.888C41.536 81.2587 42.496 85.2267 42.496 89.792C42.496 94.3573 41.536 98.3253 39.616 101.696C37.7387 105.024 35.008 107.584 31.424 109.376C27.8827 111.125 23.68 112 18.816 112H4.92799V67.392H18.816ZM18.816 107.2C24.576 107.2 28.9707 105.685 32 102.656C35.0293 99.584 36.544 95.296 36.544 89.792C36.544 84.2453 35.008 79.9147 31.936 76.8C28.9067 73.6854 24.5333 72.128 18.816 72.128H10.752V107.2H18.816Z" stroke="white"/>
  <path d="M82.178 93.12C82.178 94.2293 82.114 95.4027 81.986 96.64H53.954C54.1673 100.096 55.3406 102.805 57.474 104.768C59.65 106.688 62.274 107.648 65.346 107.648C67.8633 107.648 69.954 107.072 71.618 105.92C73.3247 104.725 74.5193 103.147 75.202 101.184H81.474C80.5353 104.555 78.658 107.307 75.842 109.44C73.026 111.531 69.5273 112.576 65.346 112.576C62.018 112.576 59.0313 111.829 56.386 110.336C53.7833 108.843 51.7353 106.731 50.242 104C48.7487 101.227 48.002 98.0267 48.002 94.4C48.002 90.7733 48.7273 87.5947 50.178 84.864C51.6287 82.1333 53.6553 80.0427 56.258 78.592C58.9033 77.0987 61.9327 76.352 65.346 76.352C68.674 76.352 71.618 77.0773 74.178 78.528C76.738 79.9787 78.7007 81.984 80.066 84.544C81.474 87.0613 82.178 89.92 82.178 93.12ZM76.162 91.904C76.162 89.6853 75.6713 87.7867 74.69 86.208C73.7087 84.5867 72.3647 83.3707 70.658 82.56C68.994 81.7067 67.138 81.28 65.09 81.28C62.146 81.28 59.6287 82.2187 57.538 84.096C55.49 85.9733 54.3167 88.576 54.018 91.904H76.162Z" stroke="white"/>
  <path d="M102.921 106.624L113.801 76.928H120.009L106.249 112H99.4655L85.7055 76.928H91.9775L102.921 106.624Z" stroke="white"/>
  <path d="M157.74 93.12C157.74 94.2293 157.676 95.4027 157.548 96.64H129.516C129.73 100.096 130.903 102.805 133.036 104.768C135.212 106.688 137.836 107.648 140.908 107.648C143.426 107.648 145.516 107.072 147.18 105.92C148.887 104.725 150.082 103.147 150.764 101.184H157.036C156.098 104.555 154.22 107.307 151.404 109.44C148.588 111.531 145.09 112.576 140.908 112.576C137.58 112.576 134.594 111.829 131.948 110.336C129.346 108.843 127.298 106.731 125.804 104C124.311 101.227 123.564 98.0267 123.564 94.4C123.564 90.7733 124.29 87.5947 125.74 84.864C127.191 82.1333 129.218 80.0427 131.82 78.592C134.466 77.0987 137.495 76.352 140.908 76.352C144.236 76.352 147.18 77.0773 149.74 78.528C152.3 79.9787 154.263 81.984 155.628 84.544C157.036 87.0613 157.74 89.92 157.74 93.12ZM151.724 91.904C151.724 89.6853 151.234 87.7867 150.252 86.208C149.271 84.5867 147.927 83.3707 146.22 82.56C144.556 81.7067 142.7 81.28 140.652 81.28C137.708 81.28 135.191 82.2187 133.1 84.096C131.052 85.9733 129.879 88.576 129.58 91.904H151.724Z" stroke="white"/>
  <path d="M171.252 64.64V112H165.428V64.64H171.252Z" stroke="white"/>
  <path d="M196.474 112.576C193.189 112.576 190.202 111.829 187.514 110.336C184.869 108.843 182.778 106.731 181.242 104C179.749 101.227 179.002 98.0267 179.002 94.4C179.002 90.816 179.77 87.6587 181.306 84.928C182.885 82.1547 185.018 80.0427 187.706 78.592C190.394 77.0987 193.402 76.352 196.73 76.352C200.058 76.352 203.066 77.0987 205.754 78.592C208.442 80.0427 210.554 82.1333 212.09 84.864C213.669 87.5947 214.458 90.7733 214.458 94.4C214.458 98.0267 213.647 101.227 212.026 104C210.447 106.731 208.293 108.843 205.562 110.336C202.831 111.829 199.802 112.576 196.474 112.576ZM196.474 107.456C198.565 107.456 200.527 106.965 202.362 105.984C204.197 105.003 205.669 103.531 206.778 101.568C207.93 99.6053 208.506 97.216 208.506 94.4C208.506 91.584 207.951 89.1947 206.842 87.232C205.733 85.2693 204.282 83.8187 202.49 82.88C200.698 81.8987 198.757 81.408 196.666 81.408C194.533 81.408 192.57 81.8987 190.778 82.88C189.029 83.8187 187.621 85.2693 186.554 87.232C185.487 89.1947 184.954 91.584 184.954 94.4C184.954 97.2587 185.466 99.6694 186.49 101.632C187.557 103.595 188.965 105.067 190.714 106.048C192.463 106.987 194.383 107.456 196.474 107.456Z" stroke="white"/>
  <path d="M227.939 83.392C229.091 81.3867 230.798 79.7227 233.059 78.4C235.363 77.0347 238.03 76.352 241.059 76.352C244.174 76.352 246.99 77.0987 249.507 78.592C252.067 80.0853 254.073 82.1973 255.523 84.928C256.974 87.616 257.699 90.752 257.699 94.336C257.699 97.8773 256.974 101.035 255.523 103.808C254.073 106.581 252.067 108.736 249.507 110.272C246.99 111.808 244.174 112.576 241.059 112.576C238.073 112.576 235.427 111.915 233.123 110.592C230.862 109.227 229.134 107.541 227.939 105.536V128.64H222.115V76.928H227.939V83.392ZM251.747 94.336C251.747 91.6907 251.214 89.3867 250.147 87.424C249.081 85.4613 247.63 83.968 245.795 82.944C244.003 81.92 242.019 81.408 239.843 81.408C237.71 81.408 235.726 81.9413 233.891 83.008C232.099 84.032 230.649 85.5467 229.539 87.552C228.473 89.5147 227.939 91.7973 227.939 94.4C227.939 97.0453 228.473 99.3707 229.539 101.376C230.649 103.339 232.099 104.853 233.891 105.92C235.726 106.944 237.71 107.456 239.843 107.456C242.019 107.456 244.003 106.944 245.795 105.92C247.63 104.853 249.081 103.339 250.147 101.376C251.214 99.3707 251.747 97.024 251.747 94.336Z" stroke="white"/>
  <path d="M271.19 83.392C272.342 81.3867 274.048 79.7227 276.31 78.4C278.614 77.0347 281.28 76.352 284.31 76.352C287.424 76.352 290.24 77.0987 292.758 78.592C295.318 80.0853 297.323 82.1973 298.773 84.928C300.224 87.616 300.949 90.752 300.949 94.336C300.949 97.8773 300.224 101.035 298.773 103.808C297.323 106.581 295.318 108.736 292.758 110.272C290.24 111.808 287.424 112.576 284.31 112.576C281.323 112.576 278.677 111.915 276.373 110.592C274.112 109.227 272.384 107.541 271.19 105.536V128.64H265.365V76.928H271.19V83.392ZM294.997 94.336C294.997 91.6907 294.464 89.3867 293.397 87.424C292.331 85.4613 290.88 83.968 289.045 82.944C287.253 81.92 285.27 81.408 283.094 81.408C280.96 81.408 278.976 81.9413 277.141 83.008C275.349 84.032 273.899 85.5467 272.789 87.552C271.723 89.5147 271.19 91.7973 271.19 94.4C271.19 97.0453 271.723 99.3707 272.789 101.376C273.899 103.339 275.349 104.853 277.141 105.92C278.976 106.944 280.96 107.456 283.094 107.456C285.27 107.456 287.253 106.944 289.045 105.92C290.88 104.853 292.331 103.339 293.397 101.376C294.464 99.3707 294.997 97.024 294.997 94.336Z" stroke="white"/>
  <path d="M340.615 93.12C340.615 94.2293 340.551 95.4027 340.423 96.64H312.391C312.605 100.096 313.778 102.805 315.911 104.768C318.087 106.688 320.712 107.648 323.784 107.648C326.301 107.648 328.391 107.072 330.055 105.92C331.762 104.725 332.957 103.147 333.639 101.184H339.911C338.973 104.555 337.095 107.307 334.279 109.44C331.463 111.531 327.965 112.576 323.784 112.576C320.456 112.576 317.469 111.829 314.823 110.336C312.221 108.843 310.173 106.731 308.68 104C307.186 101.227 306.44 98.0267 306.44 94.4C306.44 90.7733 307.165 87.5947 308.615 84.864C310.066 82.1333 312.093 80.0427 314.695 78.592C317.341 77.0987 320.37 76.352 323.784 76.352C327.112 76.352 330.055 77.0773 332.615 78.528C335.175 79.9787 337.138 81.984 338.503 84.544C339.911 87.0613 340.615 89.92 340.615 93.12ZM334.599 91.904C334.599 89.6853 334.109 87.7867 333.128 86.208C332.146 84.5867 330.802 83.3707 329.095 82.56C327.431 81.7067 325.575 81.28 323.527 81.28C320.583 81.28 318.066 82.2187 315.975 84.096C313.927 85.9733 312.754 88.576 312.456 91.904H334.599Z" stroke="white"/>
  <path d="M354.127 82.624C355.151 80.6187 356.602 79.0613 358.479 77.952C360.399 76.8427 362.724 76.288 365.455 76.288V82.304H363.919C357.391 82.304 354.127 85.8453 354.127 92.928V112H348.303V76.928H354.127V82.624Z" stroke="white"/>
  </svg>
</div>

app/views/pages/about.html.erb
<section class="about">
  <div class="container">
    <h1 class="title">about</h1>
    <div class="profile">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum molestiae, eos facilis voluptatibus est consequatur minima sequi laborum, odio quod doloremque a ad nihil reprehenderit earum incidunt laboriosam nobis vitae, rerum officia ipsa corporis. Corporis voluptate aliquam eligendi, aut autem dolores error nam perferendis deserunt numquam, et omnis, dignissimos deleniti.</p>
    </div>
    <div class="formation-wrapper">
      <div class="formation">
        <h1 class="title">training</h1>
        <div class="wagon">
          <h4>Le Wagon Fullstack Bootcamp</h4>
          <p>2017 - Batch #82 à Lyon</p>
          <h4>Online courses completed:</h4>
          <p>
            2020 - Modern Javascript to the beginning (Udemy)
            <br>
            2020 - Modern React with Redux (Udemy)
            <br>
            2019 - React & Redux (Le Wagon)
          </p>
        </div>
      </div>
      <div class="competences">
        <div class="circle"></div>
        <h1 class="title">skills</h1>
        <%= render 'pages/wagon' %>
        <div class="card-wrapper">
          <div class="card card-white">
            <i class="fab fa-html5 fa-3x"></i>
          </div>
          <div class="card card-white">
            <i class="fab fa-css3-alt fa-3x"></i>
          </div>
          <div class="card">
            <i class="fab fa-js-square fa-3x"></i>
          </div>
          <div class="card">
            <%= image_tag('rails.png') %>
          </div>
          <div class="card">
            <i class="fab fa-node-js fa-3x"></i>
          </div>
          <div class="card">
            <i class="fab fa-react fa-3x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/animation.html.erb
<section class="animation-text">
  <div class="animation-text-container">
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
    <div class="panel"></div>
  </div>
</section>

<section class="animation">
  <h1>Animation with Gsap</h1>
  <div class="box-container">
    <svg class="b-logo" width="203px" height="203px" viewBox="0 0 203 203" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

      <g id="Welcome" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" opacity="0.99">
        <g id="Assets" transform="translate(-2185.000000, -1045.000000)">
          <g transform="translate(2187.000000, 1047.000000)">
            <circle id="Oval" stroke="#000000" stroke-width="3" fill="#FFFFFF" fill-rule="nonzero" cx="99.5" cy="99.5" r="99.5"></circle>
            <circle id="Oval" stroke="#000000" fill="#FFFFFF" fill-rule="nonzero" cx="100" cy="100" r="92"></circle>
            <text id="B" font-family="AcademyEngravedLetPlain, Academy Engraved LET" font-size="160" font-weight="normal" fill="#000000">
              <tspan x="48.3984375" y="150">B</tspan>
            </text>
          </g>
        </g>
      </g>
    </svg>
    <div class="box-text">
      <h2 class="box-title">Lorem Ipsum</h2>
      <p class="box-subtitle">Neque porro quisquam est qui dolorem ipsum quia dolor sit amet...</p>
      <button class="box-btn" >More</button>
    </div>
  </div>
</section>

<section class="animation-css">
  <h1>Animation with CSS only</h1>
  <div class="animation-container">
    <div class="wrapper-boxes">
      <div class="animated-box">
        <h3 class="fadeSlideDown">Fade Slide Down</h3>
      </div>
      <div class="animated-box ">
        <h3 class="slideDown">Slide Down</h3>
      </div>
      <div class="animated-box">
        <h3 class="expandOpen">Expand Open</h3>
      </div>
      <div class="animated-box slideLeft">
        <h3>Fade Left</h3>
      </div>
      <div class="animated-box pulse">
        <h3>Pulse</h3>
      </div>
      <div class="animated-box">
        <h3 class="fadeIn">Fade In</h3>
      </div>
      <div class="animated-box pullUp">
        <h3>Pull Up</h3>
      </div>
      <div class="animated-box pullDown">
        <h3>Pull Down</h3>
      </div>
      <div class="animated-box">
        <h3 class="bounce">Bounce</h3>
      </div>
      <div class="animated-box stretchLeft">
        <h3>Stretch Left</h3>
      </div>
      <div class="animated-box">
        <h3 class="floating">FLOATING</h3>
      </div>
      <div class="animated-box hatch">
        <h3>HATCH</h3>
      </div>
      <div class="animated-box bigEntrance">
        <h3>Big Entrance</h3>
      </div>
      <div class="animated-box">
        <h3 class="tossing">TOSSING</h3>
      </div>
      <div class="animated-box stretchRight">
        <h3>Stretch Right</h3>
      </div>
      <div class="animated-box ">
        <h3 class="stretchRight">Stretch Right</h3>
      </div>
      <div class="animated-box slideExpandUp">
        <h3>Slide Expand Out</h3>
      </div>
      <div class="animated-box expandUp">
        <h3>Expand Up</h3>
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<section class="home">
  <div class="home-boxes">
    <div class="home-link">
      <%= link_to 'WELCOME PAGES', accueil_path %>
    </div>
    <div class="home-link">
      <%= link_to 'ABOUT', about_path %>
    </div>
    <div class="home-link">
      <%= link_to 'NAVBARS', nav_path %>
    </div>
    <div class="home-link">
      <%= link_to 'FOOTERS', pieddepage_path %>
    </div>
    <div class="home-link">
      <%= link_to 'FORMS', new_reservation_path %>
    </div>
    <div class="home-link">
      <%= link_to 'CAROUSEL', carousel_path %>
    </div>
    <div class="home-link">
      <%= link_to 'CARDS', cards_path %>
    </div>
    <div class="home-link">
      <%= link_to 'ANIMATION', animation_path %>
    </div>
    <div class="home-link">
      <%= link_to 'MATRIX', matrix_path %>
    </div>
    <div class="home-link">
      <%= link_to 'STAR WARS', starwars_path %>
    </div>
    <div class="home-link">
      <%= link_to 'ICONES', icones_path %>
    </div>
    <div class="home-link">
      <%= link_to 'IMAGES', images_path %>
    </div>
    <div class="home-link">
      <%= link_to 'RESOURCES', ressource_path %>
    </div>
    <div class="home-link">
      <%= link_to 'PROJECTS', projects_path %>
    </div>
    <div class="home-link">
      <%= link_to 'PAGES 404', p404_path %>
    </div>
    <div class="home-link">
      <%= link_to 'CONTACT', contact_path %>
    </div>
  </div>
</section>

app/views/pages/images.html.erb
<div class="image-container">
  <div class="text-zone">
    <h1>BENOÎT</h1>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-header"></div>
  <div class="footer-body">
    <div class="footer-links">
      <%= link_to 'Home', root_path, class: "footer-link" %>
      <%= link_to 'Pages d\'Accueil', accueil_path, class: "footer-link" %>
      <%= link_to 'Animation', animation_path, class: "footer-link" %>
      <%= link_to 'About', about_path, class: "footer-link" %>
      <%= link_to 'Carousel', carousel_path, class: "footer-link" %>
      <%= link_to 'Cards', cards_path, class: "footer-link" %>
      <%= link_to 'Navbars', nav_path, class: "footer-link" %>
      <%= link_to 'Footers', pieddepage_path, class: "footer-link" %>
      <%= link_to 'Projects', projects_path, class: "footer-link" %>
      <%= link_to 'Forms', new_reservation_path, class: "footer-link" %>
      <%= link_to '404', p404_path , class: "footer-link"%>
      <%= link_to 'Icones', icones_path, class: "footer-link" %>
      <%= link_to 'Images', images_path, class: "footer-link" %>
      <%= link_to 'Resources', ressource_path, class: "footer-link" %>
      <%= link_to 'Matrix', matrix_path, class: "footer-link" %>
      <%= link_to 'Star Wars', starwars_path, class: "footer-link" %>
      <%= link_to 'Contact', contact_path, class: "footer-link" %>
    </div>
  </div>
  <div class="footer-footer text-center">
    <p>©ben7x7 2021</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-source">
  <div class="logo">
    <%= image_tag ('logo.png'), height: 40 %>
  </div>
  <ul class="nav-links">
    <li class="nav-item active">
      <%= link_to 'Formulaire', new_reservation_path  %>
    </li>
    <li class="nav-item">
      <%= link_to '404', p404_path  %>
    </li>
    <li class="nav-item">
      <%= link_to 'Carousel', carousel_path  %>
    </li>
    <li class="nav-item">
      <%= link_to 'Starwars', starwars_path  %>
    </li>

    <li class="nav-item">
      <%= link_to 'Matrix', matrix_path  %>
    </li>

    <li class="nav-item">
      <%= link_to about_path do %>
        <%= t(".about", default: "About") %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to projects_path do %>
        <%= t(".projects", default: "Projects") %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to contact_path do %>
        <%= t(".contact", default: "Contact") %>
      <% end %>
    </li>
  </ul>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>
</nav>